### ISSUE TITLE
Entwicklungsumgebung

### ISSUE THREAD

**Issue by Sasuke-SR** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#2]
Hey Erdem da SR ja down ist wollt ich dich fragen wo man deine Entwicklungsumgebung herbekommt?

grüße Sasuke

**Comment by rolfjoseph** [comment]
Hallo,

ja, SR ist ohne jegliche Ankündigung gelöscht worden. Krokodil wird wohl ein neues Forum Aufbauen.
Die Entwicklungsumgebung ( nun mit PHP 7.0.8 ) kannst du, wenn ich die neue fertig gestellt habe unter openwebsoccer.de dann beziehen.

Die weiteren Änderungen beziehen sich auf PHP 7, so das man PHP 7 gesetzt haben sollte ( PHP 5 also bitte nicht mehr nutzen ). Auch wurde die .htaccess Datei angepasst, so das diese bei bestimmten Webspaces wohl nicht mehr gelöscht werden muss.

Webspaces mit FCGI haben ein Problem mit iosec, daher wird iosec nur bei vorhandenen Apache-Handler nun mit eingebunden. Funktionen sind nur noch mit FUNCTION beschrieben ( z.B. FUNCTION renderView() ). Auch die zusätzliche Absicherung der Twigtemplates mittels SEC ( zuvor OPEN_WEBSOCCER ) funktioniert nun besser.

**Comment by rolfjoseph** [comment]
Definitiv läuft der OpenWebsoccer nun nicht mehr mit PHP5 ! Hier könnt ihr dies Testen:

Ja, http://70.topligclub.de/
Nein, http://56.topligclub.de/ entsprechend 55, 54 und 53.

Mit http://70.topligclub.de/bench.php könnt ihr prüfen, das wirklich die entsprechende Version genutzt wird. Die Benchzeit gilt auch als entsprechende Referenz der Ausführungszeit auf den Server.

In PHP7 darf es z.B. keine Funktion innerhalb der Klasse geben, die den gleichen Namen hat wie die Klasse selbst.

Die Twig 1.24.1.dev wurde mit 1.24.1 ersetzt ( keine Änderung im Code ). Das es noch keine Twig 2.x gibt, kann noch nicht abgesehen werden, was für Änderungen durch Twig irgendwann folgen werden.

**Comment by rolfjoseph** [comment]
Warum es halt dauert, sieht man an der neuesten strategischen Erweiterung. So wird es möglich sein native PHP-Funktionen und Filter direkt in Twig nutzen zu können. So kann man nun z.B. mit {{ ucfirst("OpenWebsoccer") }} als Funktion, oder mittels Filter {{ "Openwebsoccer"|ucfirst }} direkt in Twig die Ausgabe "OpenWebsoccer" auszugeben. Dies bringt natürlich neue Möglichkeiten für die Zukunft.

Das augenblickliche MVC-Konzeptes zur Trennung von Layout und Programmcode kann dadurch aufgebrochen werden, wo es sinnvoll oder der direkte Zugriff einfacher für die Verarbeitung sein kann. 

Es kann z.B. eine Seite für den Admin erstellt werden, wo die PHP-Informationen mittels folgender Vorlage realisiert werden kann:

{% extends "base.twig" %}
{% block page_title %}
	{{ i18n.getMessage("phpinfo_navlabel") }}
{% endblock %}
{% block page_content %}
	{{ phpinfo() }}
{% endblock %}

So natürlich für alle sichtbar, da es zur Zeit noch keine Trennung zwischen User und Admin bei der Anzeige gibt.

**Comment by sladee85** [comment]
Hey. Sagmal gibt es derzeit eine aktuellste Version deines OpenWebsoccers zum downloaden?
Wir wollten in der "Sommerpause" nun von der HSE auf OpenWebsoccer wechseln. Bietet sich einfach an ...
Oder wäre es sinvoll auf die Version bzgl. PHP 7.x.x zu warten, die du genannt hattest?
Und kannst du da schon in etwa sagen wann du die bereitstellst? :)
Danke!

**Comment by rolfjoseph** [comment]
Auf http://mangetsuleague.topligclub.de/ läuft gerade der Test. Sieht natürlich wie die Vorgängerversion aus, aber unter der Haube sind ja die Veränderungen.

So kann man nun z.B. im Template auch mal eine Variable mittels des Twig-Befehls set oder wie in diesem Fall die gesetzte Nachricht in der Funktion überprüfen. 

{{ print_r(i18n.getMessage("messages_new_messages", unseenMessages)) }}

PHP-Funktionen die durch einen einfachen Aufruf  zu einer Ausgabe führen, sind somit easy einsetzbar.

Mit {{ print_r(getrusage()) }} kann man z.B. die CPU-Belastung anzeigen lassen. {{ sleep(3) }} sollte auch funktionieren.

**Comment by sladee85** [comment]
Mit der nächsten zu Verfügung gestellten Version springen wir dann mit auf ... und testen fleissig mit! ;)

**Comment by rolfjoseph** [comment]
Es dauert wohl noch eine Woche.

macro bezeichnet in Tewig eine Funktion, die jedoch gegenüber der Funktion in PHP, keinen Zugriff auf die Variablen im aktuellen Twig-Template hat. Mit einem zusätzlichen macro ( Funktion ) ist nun folgendes möglich, was gerade auch das Testen etwas vereinfachen bzw. auch als Ausgabe dienen kann.

Zuerst wird im Template das Template macro.twig mit  {% import "macro.twig" as macro %} ganz oben eingebunden. Im Template selbst muss nun eine globale Variable "var" mit Inhalt befüllt werden und dann mit dem Macro ausgegeben werden:

{% set var = env.getConfig("context_root") %}
{{ macro.var(_context) }}

Hiermit erhalten wird also den Context-Root-Pfad.

Da im Websoccer wenige Macros definiert sind, werden diese in die macro.twig mit eingebunden, so das sich eine kleine Library ergibt. Der Aufruft dieser definierten "Twig-Funktionen" ist dann also macro.xxx . Entsprechend werden also die vorhandenen Bezeichnungen angepasst. Im Gegensatz zu profilelements.infofield ist dann die Lesbarkeit dann doch einfacher mit macro.infofield. Gleichzeitig können in vielen Dateien mehrere imports vermieden werden, was ebenfalls zu mehr Übersicht führt.

**Comment by rolfjoseph** [comment]
Hier die  Ergänzung zur GitHub-Seite:

## PHP 7 - neue Möglichkeiten

In PHP 7 sind Neuerungen enthalten, welche nicht in PHP 5 mehr unterstützt werden. Einige Funktionen aus PHP 5 werden zudem nicht in PHP 7 unterstützt. Die Folge ist, das durch die Entwicklung der OpenWebsoccer nicht mehr auf PHP 5 läuft, ohne Anpassungen vorzunehmen. Um den Code nicht mit der Kompatibilität zu PHP 5 zu überfrachten, wird auf die PHP 5 Unterstützung verzichtet.

Einer der wichtigen Neuerungen ist z.B. die Nutzung von Konstanten. In PHP 7 sind nun auch Konstanten-Array´s einfach zu definieren. Hierdurch wurde es erst möglich die starre Struktur für die Verzeichnisssuche bei Definitionen aufzubrechen. Der Code für die Suche nach den Templates ist nun deutlich kleiner und einfacher. Genau diese Veränderung führt unter PHP 5 zu folgender Fehlermeldung:
Warning: Constants may only evaluate to scalar values.

**Comment by rolfjoseph** [comment]
Hier könnt ihr nun die aktuelle Fassung downloaden:

https://github.com/rolfjoseph/OpenWebsoccer-2016-PHP-7-

Build: 2016.7.11
- Unterstützung von nativen PHP Funktionen in Twig
- alle Makros in macro.twig zusammengefasst
- Definition für FUCKTION eingeführt und umgesetzt
- Twig 1.24.1

Läuft nur noch auf PHP 7, da neue Möglichkeiten genutzt werden und auf deprecated Funktionen verzichtet wird. PHP 5 wird ab August 2016 nicht mehr weiter entwickelt. Dagegen ist PHP 7.1 schon im RC, wo der OpenWebsoccer im RC1 läuft.

**Comment by rolfjoseph** [comment]
Der gesamte GitHub Inhalt wurde aktualisiert. Hinweise dazu sind in den Commits. Auch hier wurde die Umstellung auf PHP7 berücksichtigt. Die Websoccer-Tools sind daher obsolet geworden.

**Comment by rolfjoseph** [comment]
Grav wurde frisch auf 1.1.0 bereitgestellt und hier ebenfalls im OpenWebsoccer vorkonfiguriert zu Verfügung gestellt.

**Comment by rolfjoseph** [comment]
Version 2016.8.10 out now. "Im Prinzip das OpenWebsoccer 2016 PHP 7 Turbo"

https://github.com/rolfjoseph/OpenWebsoccer-2016-PHP-7-/commit/ce5f7c7f5eaccf98ef94db4468edbf5778c0d374

Der OpenWebsoccer ohne Template Cache-Dateien, der eigenen Twig-Funktions-Library mit zusätzlichen Möglichkeiten der Programmierung. Seht auch oben beim Link.

**Comment by rolfjoseph** [comment]
Die OpenWebsoccer 2016 PHP 7 Entwicklungsumgebung steht nun zur Verfügung.

http://openwebsoccer.de/owside.exe
