### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by kosak83** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#3]
Lieber erdemcan

Vielen Dank für deinen grossen Einsatz beim. Update des Websoccers auf php7.  Ich hätte eine Frage betreffend der Anzeige des Websoccers auf Mobilgeräten.  Im klassischen Websoccer von Ingo sah der Websoccer auch auf mobilen Geräten toll aus,  mit dem Open Websoccer hat es allerdings einige Darstellungsprobleme.  Lässt sich dies evtl. ändern?

**Comment by rolfjoseph** [comment]
Natürlich ist meine Version klar für den Desktop optimiert. Das Problem dabei ist, wenn man an die gleichen Informationen bei der anzeige auf mobilen Geräten haben will, geht dies nicht. Mann muss dann diese auf vielen Tabs verteilen. Das sieht zwar besser auf mobilen Geräten aus, bringt aber deutlich mehr Klickerei auf dem Desktop mit sich ( Beispiel OFM ).

Ich habe selbst einen Sony Z2 und komme sehr gut damit zurecht. Ab einem Tablet gibt es ja sowieso keine Einschränkungen bei der Bedienung. Es ist zwar üblich mit dem Smartfon zu arbeiten, allerdings achten viele nicht mehr auf die Mitmenschen und dem Straßenverkehr. Ausschließliches Websoccer spielen mimt Smartfons möchte ich daher eher vermeiden.

Wenn du die Darstellungsprobleme genau aufzeigst, kann ich eher sagen, ob eine Anpassung möglich ist. Responsiv bedeutet ja gleiches Aussehen auf allen Geräten, aber Bedingt halt auch Abstriche bei der Gestaltung. Darüber hinaus muss man sich laufend Gedanken machen, wenn man etwas neues Einbaut, ob dies dann auch auf mobilen Geräten gleich aussieht, oder weitete Anpassungen am Design gemacht werden müssen.

Die Zeit ist besser für Verbesserungen einzusetzen, anstatt für das Handling am Smartfon. Wir haben hier ja nicht die große Anzahl an Mitprogrammierer. Sehr viele Dinge sind immer noch nicht umgesetzt. Je nach Server gibt es immer wieder mal Besonderheiten. So wird das Login z.B. auf einen Server total falsch ausgeführt, was auch beim alten Websoccer nicht funktioniert. Das Problem ist schon erkannt, aber noch nicht gelöst.
