### ISSUE TITLE
Installation Ordner Problem

### ISSUE THREAD

**Issue by bornhaeusser** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#5]
Ich versuche Openwebsocker zu installieren. Leider komme ich nicht über den Schritt bei der Ordnerberechtigung da diese anscheint nicht stimmt.

Habt ihr einen Tipp für mich 
(Linux, Debian)

Anforderung	Erforderlicher Wert	Tatsächlicher Wert
PHP	7.0.0	7.0.9-1
JSON-Unterstützung in PHP ist aktiviert	Ja	Ja
PHP Bibliothek GD ist installiert	Ja	Ja
PHP-Konfigurtion: safe_mode	off	off
Datei/Ordner hat Schreibrechte (in Linux, führe aus: CHMOD a+w ): generated/	Ja	Nein

Alle weiteren Ordner sind auch anscheinend nicht beschreibbar.

**Comment by bornhaeusser** [comment]
changed index.php in install folder

define('BASE_FOLDER', $_SERVER['DOCUMENT_ROOT'].'/');

**Comment by rolfjoseph** [comment]
Gut das es geklappt hat. Anscheinend hast du nicht das OpenWebsoccer Verzeichnis hoch geladen, sondern nur den Inhalt. Die original Zeile ist ja "define('BASE_FOLDER', $_SERVER['DOCUMENT_ROOT'].'/openwebsoccer/');"

Das hat schon seinen Grund, warum dies so ist. Niemals den Inhalt eines Verzeichnisses in den Root legen, sondern über die Domain auf das Verzeichnis zeigen. Nur so kann auch z.B. Grav oder mögliche andere Programme angesprochen werden. Nachträglich kann man das Verzeichnis eh anpassen, sofern dies im Admincenter so hinterlegt ist. Auch aus Sicherheitsgründen ist dies so, da sonst alle Unterverzeichnisse von der .htaccess betroffen werden.

Danke für Deine Rückmeldung !
