### ISSUE TITLE
Probleme nach dem Update

### ISSUE THREAD

**Issue by Kevin199224** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#6]
Hallo,
nachdem ich die neuste Version drauf habe zeigt er mir folgenden Fehler an:

Fatal error: Class 'WebSoccer' not found in /home/webpages/lima-city/soccer-chef/default-website/openwebsoccer/admin/config/global.inc.php on line 78

Wenn ich diese Datei öffne erscheint mir alles in Ordnung aber. Ausdruck Zeile 75 - 80
$action = null;
$block = null;
try {
	$website = WebSoccer::getInstance();
	if (!file_exists(CONFIGCACHE_FILE_FRONTEND)) {
		$website->resetConfigCache();

Wo liegt denn da der Fehler?

**Comment by rolfjoseph** [comment]
Alles richtig, aber du hast nicht bedacht das dein Webhoster kein PHP 7 hat, die ist PHP 5.6.24 !
Daher kann es nicht funktionieren. Lade mal auf http://openwebsoccer.de/ die Entwicklungsumgebung runter und Du wirst sehen, das es auf PHP 7 läuft.

Der Hintergrund ist, das die Verzeichnisse automatisch ermittelt werden, so das

BASE_FOLDER . '/modules/' . '/formation/',
BASE_FOLDER . '/modules/' . '/formauthentication/',
BASE_FOLDER . '/modules/' . '/freeclubs/',
BASE_FOLDER . '/modules/' . '/frontend/',
BASE_FOLDER . '/modules/' . '/frontendads/',
BASE_FOLDER . '/modules/' . '/generator/',

nicht mehr definiert werden müssen. So kann man Module rausnehmen oder einfach reinkopieren und werden automatisch gefunden. Das geht aber mit der Funktion nur in PHP 7. Deshalb heißt die Version auch OpenWebsoccer 2016 PHP 7.

**Comment by Kevin199224** [comment]
D.h also ich bin gezwungen auf PHP7 umzusteigen? Oder geht es auch anders noch?

**Comment by rolfjoseph** [comment]
Ja, du musst einen Hoster mit PHP 7 haben. PHP 5 Programme laufen auch nicht auf PHP 7, sofern sie Funktionen auf PHP 5-Basis nutzen, die in PHP 7 nicht mehr vorhanden sind.

Einzig auf PHP 5 kannst du die alternative Twig Konfiguration probieren. Siehe im lib Verzeichnis den Ordner "TwigFunctions_And_Alternative_Twig_Configuration". Die Dateien müssen entsprechend ins Verzeichnis Twig kopiert werden. Dann läuft der Websoccer im Stream-Modus, sofern der Freehoster mit seiner Server-Konfiguration da mitspielt.

Falls du Grav benutzt, so kann man dies ebenfalls in dortige Twig Verzeichnis kopieren. In der nächsten mitgelieferten Grav Version ist dies dann schon enthalten.

**Comment by Kevin199224** [comment]
Erstmal vielen Dank.
Trotz deines Tipps bleibt der Fehler leider

**Comment by rolfjoseph** [comment]
Der Tipp bezog sich nur auf die alte Installation, da diese ja auf PHP 5 läuft. Die alternative Twig Konfiguration, sollte auf allen Websoccern funktionieren. Auf meine alte HSE-Installation ist dies angewendet, so das diese ebenfalls im Stream-Modus läuft. Ich habe dies nur nicht auf PHP 5 probiert.

OK, dann schließe ich nun hier.
