### ISSUE TITLE
Table with a Leagues Ranking

### ISSUE THREAD

**Issue by Requiao** [rolfjoseph/OpenWebsoccer-2016-PHP-7-#7]
You can create a table with a ranking of the best leagues coefficients? As one of UEFA ranking where the best leagues have more vacancies in the Champions League.

like this:
![screen-shot-2015-12-09-at-11 59 23-pm](https://cloud.githubusercontent.com/assets/22676363/19336234/21270630-90e0-11e6-8b52-a8ca492e00f9.png)

**Comment by rolfjoseph** [comment]
Lichtenstein is by the way to high at this ranking. This ist for my project not nessassary and can programm by yourself.
